### ISSUE TITLE
Add labels to Restyler pull requests

### ISSUE THREAD

**Issue by abinoda** [restyled-io/restyled.io#121]
Is there a way to specify labels that should be added automatically to pull requests created by Restyler?

**Comment by pbrisbin** [comment]
No, but that's a great idea. Can you say more about how you'd like that to work?

**Comment by abinoda** [comment]
@pbrisbin It'd be great if you could just specify labels in the YAML configuration, and then have Restyler automatically tag the PRs it creates with those labels.

The use case is that we have a lot of automation set up, and we don't always want those bots to run or notify us for pull requests created by Restyler.

**Comment by pbrisbin** [comment]
Makes total sense. I think I've got it implemented in the referenced PR. I'll try to test it out and get it shipped today. Thanks!

**Comment by pbrisbin** [comment]
Looks like it works: https://github.com/restyled-io/demo/pull/35.

If you configure non-existent labels, it seems to create them if needed too.
