### ISSUE TITLE
php-cs-fixer error

### ISSUE THREAD

**Issue by kilip** [restyled-io/restyled.io#140]
Hi,

I have an error when build with php-cs-fixer. Here's an error build for this issue:
https://restyled.io/gh/kilip/repos/doyo-user-bundle/jobs/14804

**Comment by pbrisbin** [comment]
Thanks for the report. I'll look into this this week. Do you have any more information about how you've configured things? Are these custom rules? If not, do you know of a minimum version of php-cs-fixer that is needed to know of them?

**Comment by kilip** [comment]
@pbrisbin,

I have configure php-cs-fixer in this [.phpcs.dist](https://github.com/kilip/doyo-user-bundle/blob/master/.php_cs.dist) file which I think also used by restyled.
I don't have any custom rules in my .php_cs.dist..

I use the same php-cs-fixer version: 2.4.1 as defined in [restylers/php-cs-fixer](https://github.com/restyled-io/restylers/blob/2828290a87cfb6feacd5650f183e87385a23913a/php-cs-fixer/Dockerfile#L4)

**Comment by pbrisbin** [comment]
Awesome, thanks for that! My current theory is there are some packages that provide those rules that I don't have installed in the restyler image. Did you have to install anything else to get (e.g.) the [`Symfony` ruleset](https://github.com/kilip/doyo-user-bundle/blob/master/.php_cs.dist#L26) available, or does everything there just come in php-cs-fixer already?

**Comment by pbrisbin** [comment]
Oh, it looks like it was an out of date issue. Here's the version of the current restyler image:

```console
% docker run --rm --volume $PWD:/code restyled/restyler-php-cs-fixer php-cs-fixer --version      
PHP CS Fixer 2.10.4 Bowling Bear by Fabien Potencier and Dariusz Ruminski (b2dce1d)
```

After updating, I get this:

```console
% docker run --rm --volume $PWD:/code restyled/restyler-php-cs-fixer php-cs-fixer --version
PHP CS Fixer 2.14.2 Sunrise by Fabien Potencier and Dariusz Ruminski (ff401e5)
```

And it successfully runs on your code. I will push this update out in a few minutes.

Sorry for the trouble!

**Comment by pbrisbin** [comment]
For future reference, you can always see tool versions here: https://github.com/restyled-io/restyled.io/wiki/Available-Restylers

**Comment by pbrisbin** [comment]
@kilip I took the liberty of re-running the failed job to confirm the fix. It's looks good to me: https://restyled.io/gh/kilip/repos/doyo-user-bundle/jobs/15313
