### ISSUE TITLE
Prettier Restyler: Support Markdown Formatting

### ISSUE THREAD

**Issue by sanssecours** [restyled-io/restyled.io#160]
👋 Hi,

thank you for creating this really helpful tool. It would be great, if you could add Markdown support to the `prettier` restyler. Alternatively, adding a separate reformatter that only considers Markdown code and uses `prettier` would work for my use case too.

**Comment by pbrisbin** [comment]
I didn't know prettier supported Markdown, that's great! Consider it on my TODO list to get that going.

> Alternatively, adding a separate reformatter that only considers Markdown code and uses prettier would work for my use case too.

I'm struggling with the same decision in #137 actually. If you have an opinion if the `prettier` Restyler should "do it all", or if individual Restylers that are prettier-based is better, please let me know.

**Comment by pbrisbin** [comment]
Now that GH has org-level Projects, we can put Issues in the repository they belong, so I've moved this one over to the restylers repo.
