### ISSUE TITLE
Restyler: pre-commit

### ISSUE THREAD

**Issue by sloria** [restyled-io/restyled.io#164]
pre-commit (https://pre-commit.com/) is a multi-language package manager for pre-commit hooks which are typically used to format code.

Adding pre-commit support to restyled would leverage the large ecosystem of formatters that pre-commit already supports.

See past discussion of this idea here: https://github.com/pre-commit/pre-commit.github.io/issues/211

**Comment by pbrisbin** [comment]
Thanks for bring this up! I'll definitely take a look.

**Comment by pbrisbin** [comment]
Just moved this Issue over to the restylers repo -- still plan to take a look at this!
