### ISSUE TITLE
https://restyled.io/profile not seeing new organisation

### ISSUE THREAD

**Issue by vadi2** [restyled-io/restyled.io#165]
I've installed restyled for a second open-source organisation I'm part of, but `https://restyled.io/profile` is not seeing it. How can I force a refresh?

I've double-checked that restyled is installed correctly in that organisations account and it does have access to at least one repository.

**Comment by pbrisbin** [comment]
Hey, sorry for the confusion here! Is your membership in this organization public? Can you tell me the org name so I can investigate? Are you receiving Restyles in that Org, i.e. is it _just_ the Profile view that's not working?

**Comment by vadi2** [comment]
It's health-validator that is the other organisation. Not getting and restyles either!

**Comment by vadi2** [comment]
It does work for the Mudlet organisation that I'm also part of and sends restyles there.

**Comment by pbrisbin** [comment]
Thanks! On my side, it does show up that you've installed, so that much looks good. Let's set aside the Profile view for the moment and focus on why you're not actually getting Restyles...

Is the installation set up for all repositories or did you pick specific repositories to grant Restyled access to? Can you link me to a repo/pull request where you would've expected Restyled to run?

**Comment by vadi2** [comment]
It is https://github.com/health-validator/Hammer - I'd be surprised if there was nothing to do, but perhaps it is possible!

**Comment by pbrisbin** [comment]
Thanks for that! But can you link me to a Pull Request in that repo where you would've expected Restyled to run?

Some other questions I've asked so far, just in case you missed them:

- Is your membership in this organization public? 
- Is the installation set up for all repositories, or did you pick specific repositories to grant Restyled access to?

Thanks!

**Comment by vadi2** [comment]
The membership was private, changed it now. I haven't sent in a PR yet, perhaps that's the problem?

I picked a specific repository.

**Comment by pbrisbin** [comment]
> I haven't sent in a PR yet

Ah yes, I think I see now.

The Profile page can only show public organizations (at the moment). GitHub's API is unusual here and I've got to do some more work to get private orgs to show up. Now that you've published it, and if you give it 5 or so minutes to sync, you _should_ see it on your Profile page now.

Other than that though, nothing would happen until you open a PR for Restyle to run on. So hopefully, if you do that, you'll see it happen :)

**Comment by vadi2** [comment]
Makes sense. Thanks for this tool, it's great :ok_hand:
