### ISSUE TITLE
Brittany 0.12 missing on docker hub

### ISSUE THREAD

**Issue by adamjuhasz** [restyled-io/restyled.io#170]
Thanks for letting us choose the image version (https://github.com/restyled-io/restyled.io/wiki/Restyler-Versions) 

In the documentation it talks about using version 0.12.0.0 brittany, but this image doesn't seem to be on docker hub.

```
$ docker pull restyled/restyler-brittany:v0.12.0.0-beta
Error response from daemon: manifest for restyled/restyler-brittany:v0.12.0.0-beta not found
```

https://hub.docker.com/r/restyled/restyler-brittany/tags

**Comment by adamjuhasz** [comment]
🤦‍♂️ I should have read one section lower, my bad.

**Comment by pbrisbin** [comment]
Haha, I'm glad you found out! Some minor follow-ups:

- I need to get an 0.12 Restyler released, I'm itching for it too :)
- I should make it clearer in the docs that example was a hypothetical and not something real
