### ISSUE TITLE
Restyled still open new PR although it is disabled

### ISSUE THREAD

**Issue by DanielHabenicht** [restyled-io/restyled.io#192]
Hi again. 
I have enabled restyled for this repo: https://github.com/T-Systems-MMS/phonebook (for testing) 

Now I have added a `.restyled.yaml` with `enabled: false` but restyled still opens new PR's if a commit is made to another PR.

**Comment by pbrisbin** [comment]
Restyled is only aware of the `.restyled.yaml` in the specific PR it is processing. If you're trying to disable everything via a configuration file, and you have open PRs, you'll want to:

- Commit the `.restyled.yaml` to `master`
- Perform a `git fetch && git rebase origin/master && git push --force-with-lease` in each open PR

That will update those PRs with the new configuration you added in master, then Restyled should stop. Please let me know if this doesn't work.

**Comment by DanielHabenicht** [comment]
Ahh, ok good to know. Is this documented?

**Comment by pbrisbin** [comment]
Not specifically, but i could add a note to the Disabling page. I guess I
assumed it'd be clear Restyled could only see within the PR being
processed, but it makes sense that it's not obvious.

**Comment by pbrisbin** [comment]
Created a new issue to track that docs fix. Thanks for raising this!
