### ISSUE TITLE
Error downloading `https://static.rust-lang.org/dist/2019-12-20/channel-rust-nightly.toml.sha256`

### ISSUE THREAD

**Issue by drmingdrmer** [restyled-io/restyled.io#196]
Hi guys! I've been having this error every time.

The failure page is https://restyled.io/gh/openacid/repos/celeritasdb/jobs/258172

And it fails because it can not download this file: `https://static.rust-lang.org/dist/2019-12-20/channel-rust-nightly.toml.sha256`. But from my laptop, I can download it.

It didn't provide more info about the `trying to connect` error. What should I do to get rid of this failure? Thanks, guys!

```
stderrStatus: Downloaded newer image for restyled/restyler-rustfmt:v1.4.11-nightly
stderrWARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
stderrinfo: syncing channel updates for 'nightly-2019-12-20-x86_64-unknown-linux-musl'
stderrerror: could not download file from 'https://static.rust-lang.org/dist/2019-12-20/channel-rust-nightly.toml.sha256' to '/usr/local/rustup/tmp/waix0a_5hjbunj3u_file'
stderrerror: caused by: failed to make network request
stderrerror: caused by: https://static.rust-lang.org/dist/2019-12-20/channel-rust-nightly.toml.sha256: error trying to connect: failed to lookup address information: Try again
stderrerror: caused by: failed to lookup address information: Try again
stdoutSetting status of error for fe8ce61
stderrWe had trouble with the rustfmt restyler:
```

**Comment by pbrisbin** [comment]
Hi there, sorry for the trouble!

Restylers are run without networking for security reasons (to protect against a malicious image doing something with the private repo code it runs on). This is an inconvenient limitation for some tools that expect to self update or download global configuration as part of the auto formatting process, but it's not a limitation I'm comfortable removing at this time.

So the fix here is that rustfmt should not be attempting this to begin with. 

Do you happen to know why rustfmt would be trying to sync or update something as part of formatting? Is there a flag or env var we can set to disable that? I apologize, I'm not a Rust developer so I'm not sure how the tooling works.

**Comment by drmingdrmer** [comment]
I've been using the nightly build of rust. In the root of my repo there is a `rust-toolchain` file specifying which version of rust to use:

```
cat rust-toolchain
nightly-2019-12-20
```

I think it is the reason it tries to install the rustfmt built with this version of rust.

Also I noticed that there is a piece of error message as following:
```
stdoutRestyling ["components/epaxos/src/replica/exec.rs","components/epaxos/src/replica/replica.rs","components/epaxos/src/replica/test_exec.rs","components/epaxos/src/testutil.rs","src/server/server.rs"] via "rustfmt"
stderrUnable to find image 'restyled/restyler-rustfmt:v1.4.11-nightly' locally
```

I am not very familiar with docker. Would having the image `restyled/restyler-rustfmt:v1.4.11-nightly` locally be a solution to this problem?

**Comment by pbrisbin** [comment]
The `Unable to find image` message is not an error. It just means you were the first Restyled job to use that image on that particular Restyle Machine, so it had to do its one-time pull as part of your job.

You can see it proceed to pull successfully immediately after
```
Unable to find image 'restyled/restyler-rustfmt:v1.4.11-nightly' locally
v1.4.11-nightly: Pulling from restyled/restyler-rustfmt
...
Status: Downloaded newer image for restyled/restyler-rustfmt:v1.4.11-nightly
```

> In the root of my repo there is a rust-toolchain file specifying which version of rust to use:

That explains it IMO. Is there any way to disable that behavior (not in your project generally, just when the Restyler invokes `rustfmt`)? Something like `rustfmt --ignore-rust-toolchain`?

**Comment by drmingdrmer** [comment]
I did not find an option like `--ignore-rust-toolchain`.
The following line seems to be the first meaningful message of this error:

```
stderrinfo: syncing channel updates for 'nightly-2019-12-20-x86_64-unknown-linux-musl'
```

It is a `rustup` output, which means in the image it runs `rustup update` or something else.
It is possible to override `rust-toolchain` file with environment variables or with cli args. Is there a way to setting up environment variable or cli args for `rustup`?

**Comment by pbrisbin** [comment]
> which means in the image it runs rustup update or something else

Unless you've customized the `.command` or `.arguments` in `restyled.yaml`, the image will only execute `rustfmt`.

https://github.com/restyled-io/restyled.io/wiki/Available-Restylers#rustfmt

My theory is that `rustfmt` _internally_ sees this toolchain file and tries to do something clever.

> Is there a way to setting up environment variable or cli args for rustup?

You can adjust how `rustfmt` is called (see the `.command` and `.arguments` I mentioned), but nothing in this image is calling `rustup`.

**Comment by pbrisbin** [comment]
I've confirmed that running a `rustfmt` installed from one toolchain in a directory configured for another, attempts to sync:

```console
% cat foo.rs
// Attributes should be on their own lines
struct CRepr {
  x: f32,y: f32,
}
% cat rust-toolchain
nightly-2019-12-20
% docker run --rm -it --volume "$PWD":/code --workdir /code restyled/restyler-rustfmt:v1.4.11-nightly sh
/code # rustfmt foo.rs
info: syncing channel updates for 'nightly-2019-12-20-x86_64-unknown-linux-musl'
info: latest update on 2019-12-20, rust version 1.42.0-nightly (0de96d37f 2019-12-19)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: installing component 'rust-std'
info: installing component 'rustc'
^C
/code # 
```

So far I've been unsuccessful in googling why that is or how to disable it. Any ideas?

**Comment by pbrisbin** [comment]
I think I got it,

```console
/code # RUSTUP_TOOLCHAIN=nightly rustfmt foo.rs --emit stdout
/code/foo.rs:

// Attributes should be on their own lines
struct CRepr {
    x: f32,
    y: f32,
}
```

I can add the env var into the Docker image, which will override any `./rust-toolchain` files present.

**Comment by pbrisbin** [comment]
Fixed by restyled-io/restylers@8ee296d2aaed4311db4d3c10244919c5e7756c15

**Comment by drmingdrmer** [comment]
😲 thank You pbrisbin! It works!

PS, I am not very sure if nightly built rustfmt is 100% compatible with the stable built one. Hope it works for everybody. `:DDD`

**Comment by pbrisbin** [comment]
> PS, I am not very sure if nightly built rustfmt is 100% compatible with the stable built one. Hope it works for everybody. :DDD

It's a good point! I think at the time I added `rustfmt` way-back-when it might've been the case that its README really pushed the `nightly`-based installation. I don't get the same sense today :shrug: 

We can certainly make a non-`nightly` Restyler image available very easily, and also change the default to that if we think it makes sense. WDYT?

**Comment by drmingdrmer** [comment]
Yes, the rust community believes a nightly built is stable enough. And it actually is.
