### ISSUE TITLE
Make restyled clean up after itself (delete closed PR branches).

### ISSUE THREAD

**Issue by iphydf** [restyled-io/restyled.io#199]
Restyled creates lots of branches, one for each PR that's not compliant (that's many, maybe most PRs). It would be good to clean those up when restyled decides to close its PR after the author pulled from it.

**Comment by pbrisbin** [comment]
Ah, this is just a regression. We always did that, but it looks like I recently broke it. I will file a Bug Issue on the restyler repo. Thanks for reporting, surprised it took this long for someone to notice!

**Comment by pbrisbin** [comment]
Replaced by https://github.com/restyled-io/restyler/issues/95.
