### ISSUE TITLE
Replace clahub with cla-assistant (clahub seems to be gone)

### ISSUE THREAD

**Issue by iphydf** [restyled-io/restyled.io#200]
https://www.clahub.com/agreements/restyled-io/restyled.io is a dead link.

**Comment by pbrisbin** [comment]
That's sad. Seems like the whole project is gone?

**Comment by iphydf** [comment]
https://github.com/clahub/clahub seems pretty dead (4 years ago). cla-assistant.io is what we use in TokTok, and so far it's still working.

**Comment by pbrisbin** [comment]
Thanks for the suggestion, I'll rename this Issue to indicate converting to that.

**Comment by pbrisbin** [comment]
> is what we use in TokTok

Just curious, is there a way to do an org-wide CLA, or do you all just make the same CLA in each of your repositories?

**Comment by iphydf** [comment]
Yes, we used to have an org-wide CLA, but stopped it for 3 reasons:
1) some people didn't quite understand what they were getting into.
2) we have some imports from other projects, and people's contributions from the past to those imported projects shouldn't be CLA'd if they sign for another project owned/maintained by toktok.
3) we want one CLA for most projects except for one (c-toxcore), where the outbound license clause needs to be slightly different.

I think for 3, you can have an org-wide CLA and override for a single repository. I haven't tried that, but I'm pretty sure it works.

**Comment by iphydf** [comment]
So now we have an org-wide CLA *and* one for each repo, which overrides the org-wide one. As an added benefit, we can now count how many people actually contributed to a particular project.

**Comment by pbrisbin** [comment]
Thanks for the info!
