### ISSUE TITLE
Feature: reference restyled PR when merged 

### ISSUE THREAD

**Issue by Jme7** [restyled-io/restyled.io#211]
This is just a small idea, but if the user merges the restyled PR, maybe restyled.io could mention the PR that it restyled? I know, it wouldn't do much, but it is a small convenience.

**Comment by Jme7** [comment]
E.g.

- Restyled: 
> Automated style fixes for #number, created by Restyled.
>
> The following restylers made fixes:
> - whitespace
> To incorporate these changes, merge this Pull Request into the original. We
recommend using the Squash or Rebase strategies.
>
> NOTE: As work continues on the original Pull Request, this process will
re-run and update (force-push) this Pull Request with updated style fixes as
necessary. If the style is fixed manually at any point (i.e. this process finds
no fixes to make), this Pull Request will be closed automatically.
>
> Sorry if this was unexpected. To disable it, see our documentation.
- User merges PR
- Restyled:
> Here is the branch you were working on: #number

**Comment by pbrisbin** [comment]
Hey there- I apologize but I'm not sure I quite understand the suggestion:

> if the user merges the restyled PR, maybe restyled.io could mention the PR that it restyled?
>
> > Here is the branch you were working on: #number

Do you mean in the commit message? A comment somewhere? Update the Restyle PR's description?

**Comment by Jme7** [comment]
A new comment in the PR. Sorry for the confusion.

**Comment by pbrisbin** [comment]
OK, I think I understand:

- You open PR `#123`, it has some incorrect style
- Restyled corrects it in another PR `#124`, with the description "Automated style fixes for `#123`..."
- You merge `#124` into `#123`
- Restyled adds a comment to `#124` that says (something like) "Here is the branch you were working on :`#123`"

Is that too redundant with the merged event that GitHub adds automatically?

![](https://files.pbrisbin.com/screenshots/screenshot.126736.png)

I also wonder if it's valuable since the distance between such a comment and the original PR description is not far, so the link to that original PR is already very close.

**Comment by Jme7** [comment]
Yes, that is correct. And it probably isn't that valuable, it's just for a tiny bit of convenience.

**Comment by pbrisbin** [comment]
Gotcha. I think (at least for now), this is something I'm not likely to tackle myself -- but if someone were to do the work and open a PR, I would accept it -- bonus points for making it opt-in via `restyled.yaml`.

Thanks again for the suggestion!

**Comment by Jme7** [comment]
Well, I could see what I can do to make that, although, I am not exactly the best at this.

**Comment by Jme7** [comment]
Could you give me a link to the file(s) that take care of the responces?

**Comment by pbrisbin** [comment]
Sure, I can try to offer some guidance...

This would have to happen in [restyler](https://github.com/restyled-io/restyler), the CLI that is executed for each Restyle Job.

We don't directly know that we're being called as consequence of merging a Restyle PR, but we should be able to infer it:

1. We'll know we found no differences: https://github.com/restyled-io/restyler/blob/master/src/Restyler/Main.hs#L44
2. We can see if is a Restyle PR, https://github.com/restyled-io/restyler/blob/master/src/Restyler/Main.hs#L46
3. We could check (something like) the PR's `simplePullRequestMergedAt`, http://hackage.haskell.org/package/github-0.26/docs/GitHub-Data-PullRequests.html#t:SimplePullRequest

If you reach this point, you could reasonably decide to add the comment you described. And to actually do that, I would add a new function to this module, mostly following what's already there: https://github.com/restyled-io/restyler/blob/master/src/Restyler/Comment.hs

:warning: There is one minor hiccup: I *think* `findRestyledPullRequest` only looks for open PRs. Meaning, it will be `Nothing` if it's been merged. This is relatively easy to update, but it may require changing some of the other places that use this value so they don't do something wrong when dealing with a closed PR (as one example, `closeRestyledPullRequest` might have to be updated to not close if already-closed). That said, if you go through the process of doing everything else, ignoring this hiccup, I can pitch in to address that point for you.

**Comment by Jme7** [comment]
Thanks! I will start working on this.

**Comment by Jme7** [comment]
I have been looking through this, and I have no idea how Haskell script works, so, sorry, I'm not able to do this.
