### ISSUE TITLE
how to use restyled.io without pushing to master?

### ISSUE THREAD

**Issue by monperrus** [restyled-io/restyled.io#215]
I'd like to evaluate the different configuration options of restyled, and it's not a good idea to push to master each time for such a trial and error process.

how to configure restyled.io without pushing to master?

**Comment by pbrisbin** [comment]
Can you say a little more about what sort of things you're trying to evaluate?

One option is to run Restyled locally via [`restyle-path`](https://github.com/restyled-io/restyler/blob/master/bin/restyle-path#L28), which would allow trying out configurations without pushing anything anywhere. I apologize for not having better documentation about using `restyle-path`, it's on my TODO list.

**Comment by monperrus** [comment]
> Can you say a little more about what sort of things you're trying to evaluate?

1. which formatter is the best to activate. (for https://github.com/INRIA/spoon/)
1. for a given formatter, what's the best configuration options

For this there will be many changes to be done over time to the Restyled's YAML configuration, which is better not to do in master.

**Comment by pbrisbin** [comment]
Gotcha, thanks,

For what it's worth, our suggestion is that you shouldn't do such evaluation up front. We encourage installing the Restyled App and working normally. Explicit configuration should only be required if something happens to motivate you to do so -- i.e. a Restyled PR that has undesired style fixes present. At that time, you can adjust configuration in the originating PR, see the intended effect in the Restyled PR right then, and proceed.

For (1), by default, Restyler has just about all things active. Part of Restyled's philosophy is that you may have a project that's more polyglot that you realize or that even your team is familiar with. So when the occasional not-core-competency-language area gets touched, it's nice to have Restyled keeping it consistent. The only things inactive by default are when two formatters conflict on the same file type.

For (2), we encourage running formatters without configuration to begin with, or Restyled will respect any existing configuration you have via in-repository files. Another part of Restyled's philosophy on style is that it's more about consistency than any one (subjective) choice. In this way, less configuration is better, so we encourage starting there and building up only in response to concrete needs arising.

If you do want to perform some active and up-front evaluation, I would recommend using the local Restyling process: https://github.com/restyled-io/restyled.io/wiki/Running-Restyled-Locally. The should support what you're trying to do nicely, and doesn't require committing or pushing anything anywhere.

**Comment by monperrus** [comment]
> If you do want to perform some active and up-front evaluation, I would recommend using the local Restyling process: restyled-io/restyled.io/wiki/Running-Restyled-Locally. 

Thanks for the link. It requires us to find a little more time.

> For (1), by default, Restyler has just about all things active

I understand the default use case. For our use case on Spoon, we want to do it only on Java code, and I would like to choose the most appropriate Java formatter among `astyle`, `clang-format`, `google-java-format`, `jdt`. Any suggestion on how to make this choice?

**Comment by pbrisbin** [comment]
> Any suggestion on how to make this choice?

Probably not in the way you'd like. Restyled doesn't aim or claim to have language-specific knowledge or opinions like that. It's firmly in the realm of Java programmers to have their preferred tools -- we just try to support the possible choices the best we can.

The default configuration has made the choice to enable `clang-format`; the rest would need explicit enabling. There wasn't any grand investigation that went into this choice. It was a product of what got contributed to Restyled first, and if a different winner becomes apparent over time, this choice could change.

Starting there and seeing how it goes would certainly be the non-"more time" option :wink:, which would be my suggestion.

**Comment by monperrus** [comment]
Thanks for the detailed explanation.

I'm reading again the documentation page https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled

Option `remote_files` is very interesting and looks like a potential solution:

```yaml
remote_files:
  - url: https://raw.github.com/.../hlint.yaml
    path: .hlint.yaml
```

If we host a restyled configuration file elsewhere, that would provide the level of indirection required to not change master while trial-and-erroring, something like reloading `restyled.yaml` on the fly:

```yaml
remote_files:
  - url: https://raw.github.com/.../restyled.yaml
    path: restyled.yaml
```

What do you think?

**Comment by pbrisbin** [comment]
That's a great point, I hadn't thought of that.

Unfortunately, as of now you can't use `remote_files` to bring in the `.restyled.yaml` itself. Once we know about `remote_files`, and download what's listed there, we've already processed it and don't go back to re-process it. It's a bit non-trivial as you have to consider potential loops and self-referencing, etc.

That said, doing exactly that is one option being discussed in https://github.com/restyled-io/restyler/issues/96. So maybe this is interest enough for me to tackle that task next.

**Comment by monperrus** [comment]
> That said, doing exactly that is one option being discussed in restyled-io/restyler#96. So maybe this is interest enough for me to tackle that task next.

oh nice!

**Comment by pbrisbin** [comment]
I'm going to close this task as Stale and/or obviated by restyled-io/restyler#96. That task is itself not seeing much attention, but hopefully some day. Please follow for updates there.
