### ISSUE TITLE
How to Enable restyled.io on specific branches instead of all branches?

### ISSUE THREAD

**Issue by Baneeishaque** [restyled-io/restyled.io#228]
Need **option to specify branch (preferred on yaml configuration file) that to be restyled.io** instead of all branches.

Or **option to specify branch (preferred on yaml configuration file) that to be excluded from restyled.io** process.

**Comment by pbrisbin** [comment]
Interesting feature!

Can you tell me a little more about how you'd use this?

**Comment by Baneeishaque** [comment]
![r1](https://user-images.githubusercontent.com/6133009/106876304-935c7080-66fd-11eb-9809-28c99b617274.PNG)

master is my default branch, the branches in renovate folder are created by [Renovate Bot
](https://www.whitesourcesoftware.com/free-developer-tools/renovate), and others are my feature branches.

Currently restyled.io creates PRs for all branches. I am happy that restyled.io creates PRs for master & feature branches. But, it is redundent to create PRs on Renovate Bot PR branches.

Anyway, I love restyled.io, because restyled.io bot auto closes it's PRs on deleting the associated branch. So, when i deletes Renovate Bot PR branches (after merging or closing) - restyled.io bot auto closes it's associated PRs.

**Comment by pbrisbin** [comment]
Thank you very much for the kind words, I'm glad you like Restyled!

And thank you for the details about your use-case. Bots are generally something Restyled pays attention to. We have a fixed list of bots whose PRs we ignore; I'll consider adding Renovate to that list.

That said, an option like:

```yaml
ignore_branches:
  - renovate/*
```

makes total sense to me. I've created restyled-io/restyler#129 to track that work; please subscribe to that Issue for updates on that.

In the meantime, if you can configure Renovate to apply labels to the PRs it creates, you can configure Restyled to [ignore PRs with that label](https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled#ignore-labels). Note: there's a [minor caveat](https://github.com/restyled-io/restyled.io/wiki/Common-Errors:-Labels-or-Ignore-Labels-not-working).
