### ISSUE TITLE
How to set tab indentation instead of spaces?

### ISSUE THREAD

**Issue by janbarasek** [restyled-io/restyled.io#233]
Hello, I'm trying to set tab indentation instead of spaces in the `.restyled.yaml` file, but I don't know how to do it.

Please, what should the sample configuration look like?

Real example: https://github.com/baraja-core/cms/pull/24/files

Thank you.

**Comment by pbrisbin** [comment]
Hi there-

Restyled itself doesn't control how things are formatted; it runs a set of existing auto-formatters based on the language of the changed files. This means there is not global "use tabs" setting, unfortunately, and you'll have to configure the individual auto-formatters accordingly. This can be done by creating an in-repository configuration file for that tool, or (if the tool supports it) changing the `arguments` that are passed when it's run via [`.restyled.yaml`](https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled).

In this case, `clang-format` and `prettier` ran on that PR (you can tell by the PR Description or individual commits). I did a quick google for "clang-format use tabs" and "prettier js use tabs" and they both seem to support options to turn that on. I'll let you read through that and decide how you'd like to accomplish it -- if you run into any trouble, let me know.
