### ISSUE TITLE
Github's smart "change base" functionality keeps old Restyled PRs open

### ISSUE THREAD

**Issue by mjgpy3** [restyled-io/restyled.io#246]
Hello :wave:! 

Lately I've noticed that Restyled's PRs have been remaining open if we've merged the base branch, without first merging the Restyled PR. If I didn't know any better I'd say this is due to github's new(ish) ability to change the base branch automatically when the original base was merged.

Cheers!

**Comment by mjgpy3** [comment]
If you'd like some examples, I am happy to send a link to some PRs I manually closed.

**Comment by mjgpy3** [comment]
Hmmm, maybe the particular issues I was looking at were somehow detatched... Never mind, sorry about the false report.

**Comment by pbrisbin** [comment]
Hmm, it may or may not be related to changed-base, but not closing a Restyled PR when the original PR is merged is definitely a bug. If you want me to investigate, just let me know the `org/repo#n` examples to look at!
