### ISSUE TITLE
This app doesn't do anything

### ISSUE THREAD

**Issue by tjnurmin** [restyled-io/restyled.io#290]
According to Wiki,

```
    Install from the GitHub Marketplace
    Open or push to a PR
    That's it!
```

Tried that and nothing happens. PR doesn't indicate that the app did anything. I even added a syntax error in PHP code on purpose. No results.

**Comment by pbrisbin** [comment]
Hi there-

Sorry for the trouble, but thanks for reporting. I'm happy to look into why your repository might be failing (silently) but I'll need a little more details to do so. Do you have an organization/repository? Is it public? If so, can I see a PR where you had expected Restyled to run? Could you screenshot the Marketplace installation settings page?

Thanks!
Pat

**Comment by tjnurmin** [comment]
It's a private repo - that's why I purchased Solo license for my organization.

**Comment by pbrisbin** [comment]
I will still need some details (for example the org/repo name) to investigate. Please email support@restyled.io if you don't want to post those in this Issue.

**Comment by pbrisbin** [comment]
I got your email, thank you. I discovered (and fixed) the problem, and it was not specific to you, so I'm responding here.

My database provider performed some maintenance the other day. I was expecting it but I didn't realize it would disrupt our "sync marketplace" process and require a small manual intervention. This meant your purchase was not recorded on our side, and that is why Restyled ignored your PRs. I've corrected that now and can see your purchase on our side. I expect your next PR to work correctly. Please let me know (here or via email) if that's not the case, or you have any other issues.
