### ISSUE TITLE
Can't I place restyled config file inside `.github` folder?

### ISSUE THREAD

**Issue by seonglae** [restyled-io/restyled.io#291]
Restyled is github app so config file being under `.github` folder is quite reasonable

root folder or `.github` folder

**Comment by pbrisbin** [comment]
We do support that. Which oaths did you try exactly? 

Here is where we look:

https://github.com/restyled-io/restyler/blob/5f30eb289a98552be6a39f667052b66f39fb4d16/src/Restyler/Config.hs#L294

If one of these is not working, let me know and I'll treat this as a bug.

**Comment by seonglae** [comment]
Thanks I saw [here](https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled) so I thought config in root folder only works
Thanks!

**Comment by pbrisbin** [comment]
Yeah good point, I'll update those docs!
