### ISSUE TITLE
Add restyled.yaml config slot to override the forked PR behavior from: https://github.com/restyled-io/restyled.io/wiki/2022.08.03-Attack-on-Forked-PRs

### ISSUE THREAD

**Issue by woody-apple** [restyled-io/restyled.io#300]
Thanks for your quick and prompt response to the security incident! 

Unfortunately, it looks like there are no plans to by default re-enable the fork PR workflow. I totally understand the default behavior, but could you add a config options to continue to allow this workflow as we require this workflow for the Matter SDK.

Thank you!

**Comment by pbrisbin** [comment]
It's not technically difficult, but I'm nervous about having such a flag available.

It would mean a bad actor could open a PR against your OSS project and Restyled will immediately bypass any safety mechanisms by re-opening those same commits in a new PR from a known contributor in the original repository. This is the sort of thing that has always been, and will always be, possible. The recent attacks handled by GitHub are just one example. I'd feel bad if Restyled played any part in a project being compromised that like.

You're saying you'd still enable it given those risks?

I'm starting to work on the idea outlined [here](https://github.com/restyled-io/restyled.io/issues/201#issuecomment-1204165453). I'm curious if you have any thoughts on that approach.

**Comment by woody-apple** [comment]
> It's not technically difficult, but I'm nervous about having such a flag available.
> 
> It would mean a bad actor could open a PR against your OSS project and Restyled will immediately bypass any safety mechanisms by re-opening those same commits in a new PR from a known contributor in the original repository. This is the sort of thing that has always been, and will always be, possible. The recent attacks handled by GitHub are just one example. I'd feel bad if Restyled played any part in a project being compromised that like.
> 
> You're saying you'd still enable it given those risks?
I would yes. It's important that all code going in pass style requirements, and this has worked perfectly for the last couple years. (I spent a bunch of time reading about the attack today, and I'm personally not concerned about it, and also no secrets would be exposed that would be of concern). 

> I'm starting to work on the idea outlined [here](https://github.com/restyled-io/restyled.io/issues/201#issuecomment-1204165453). I'm curious if you have any thoughts on that approach.

This sounds like a great approach for some, but it does remove the ability to have restyled be a "status check" for code style going into a repository with a fork, and PR approach? (Which I believe is quite common?) Maybe if the status check can be done on the base (upstream) repo, and the PR is created against the fork, that would work?

**Comment by pbrisbin** [comment]
Thank you for those thoughts. I think there are few points to clarify:

> no secrets would be exposed that would be of concern

This is true. But I would counter that no secrets would be exposed _today_. It's entirely possible you are making this decision now and someone else (even 5 years from now you) decides to add a secret to your project.

> PRs require reviews going in, and this type of content in a PR would be rejected immediately.

Just to be totally clear. This vector is open without any actions on your part required. A bad actor could open a PR, Restyled would create a duplicate PR, GitHub Actions would run your build on that PR, and your secrets would be stolen -- all within a few minutes, before you're even aware of the PR having been opened.

> it does remove the ability to have restyled be a "status check" for code style going into a repository with a fork

This is a great point. If all you are looking for is the status check, and you don't care about the sibling PR, this could be done safely without jumping through any hoops. If that were available (but no option to bring back the old fork-PR behavior), would that work for you?

I can pretty trivially make that so. In the exact spot I updated this morning to error the PR for a fork; I can have it emit a real status instead.

**Comment by woody-apple** [comment]
> Thank you for those thoughts. I think there are a few points to clarify (mostly because I intend to link to this thread as this topic comes up over time):
> 
> > no secrets would be exposed that would be of concern
> 
> This is true. But I would counter that no secrets would be exposed _today_. It's entirely possible you are making this decision now and someone else (even 5 years from now you) decides to add a secret to your project.

Understood, no disagreement there.

> > PRs require reviews going in, and this type of content in a PR would be rejected immediately.
> 
> Just to be totally clear: this vector is open _without any actions on your part required_. A bad actor could open a PR, Restyled would create a duplicate PR, GitHub Actions would run your build on that PR, and your secrets would be stolen -- all within a few minutes, before you're even aware of the PR having been opened.

Yup, I understand, thanks for the clarification though!

> > it does remove the ability to have restyled be a "status check" for code style going into a repository with a fork
 

> This is a great point. If all you are looking for is the status check, and you don't care about the sibling PR, this could be done safely without jumping through any hoops. If that were available (but no option to bring back the old fork-PR behavior), would that work for you?
> I can pretty trivially make that so. In the exact spot I updated this morning to error the PR for a fork; I can have it emit a real status instead.

That would be super helpful, and at least would preserve that workflow. It would mean it's a little harder for folks to re-style vs what we do today, but it does at least support the Fork/PR workflow, until you can submit the PR to the fork, instead of the upstream. :) Thanks!

**Comment by pbrisbin** [comment]
OK, I pushed that change. It should be out in less than an hour. Let me know if you find it's not working and thanks for the insight!

**Comment by woody-apple** [comment]
Thank you! I'll keep an eye out and update here :)

**Comment by woody-apple** [comment]
This does appear to be working now, thanks again! Folks are having to manually run restyle now, which is... a little extra work, but your changes are working as intended :)

**Comment by pbrisbin** [comment]
OK, I have a new idea :smile: 

I've (locally) made it so Restyler logs the diff of style fixes. This means that users can very easily manually apply those fixes themselves...

![](https://files.pbrisbin.com/screenshots/screenshot.3291802.png)

![](https://files.pbrisbin.com/screenshots/screenshot.3291913.png)

![[(https://files.pbrisbin.com/screenshots/screenshot.3292129.png)

(Ignore the `grep -v` in that last screenshot).

I think this is pretty slick, certainly better than manually running `restyler`. WDYT?

**Comment by pbrisbin** [comment]
I also realized another thing that prevents us bringing back the old behavior via configuration: a hypothetical attacker controls the configuration itself.

Restyled uses the configuration file _in the branch being restyled_. That means that, if such a configuration existed, an attacker could just enable it in their malicious PR. We could change that of course, and always read configuration from the default branch, but that brings its own trade-offs -- and there's no reason to other than to avoid this situation. I'd rather just not introduce it.
