### ISSUE TITLE
GitLab et al

### ISSUE THREAD

**Issue by pbrisbin** [restyled-io/restyled.io#76]
**WIP**: this Issue is just a scratch-pad of ideas for what it would take to support a non-GitHub service with Restyled. It is not a promise that this will happen -- that said, if anyone is down to help, please reach out!

---

The good news is things are well-decoupled (IMO), and we could tackle this in pretty clear increments without any inter-dependence. Also, if we tackled all of the generalizations to make GitLab possible, but then didn't do it, it could still be valuable as a better separation-of-concerns. We might even leverage it to have some kind Test "backend" we could swap in to solve our current lack of integration testing.

## ~~1- OAuth2~~

~~AFAICT, GitHub is the only service offering this idea of *App*s that can request tokens. Therefore, non-GitHub will require a logged-in user on Restyled with a configured Access Token. That means we need to support the service in `Yesod.Auth.OAuth2` (which is easy), and either store the Access Token from the handshake, or have some kind of *Profile* page where the user can give us Personal Access Tokens.~~

This has been shipped in`yesod-auth-oauth2`. That library has also been updated to expose the `refreshToken` so we can refresh our stored `accessToken` from login, rather than getting a totally separate PAT through some Profile mechanism.

## 2- Frontend

At first, we could require the user to manually install our webhook. I'm not sure if GitLab (et al) have APIs for installing it, if they do we can consider automating it a follow-up nice-to-have.

~~We'll just need to abstract the idea of Repo and PullRequest within the `restyled.io` codebase. Our own data exists only in terms of Owner (Name), Repo (Name), and PR (Number), for which there are obvious analogs in GitLab, so this should be relatively easy.~~ (this part's been merged) We'll just have a concrete function for turning GitLab's Payload(s) into those primitives, and we're good.

~~*One question is if we should keep using the `github` package's types (e.g. `Name Owner`). They are actually generic enough for our needs at this level (unlike when we get to Restyler), but I'm nervous about making GitHub special as the pattern everything is mapped to, rather than having a generic pattern that everything maps to with GitHub as "just another case".*~~ (we'll do this, at least for now)

## 3- Backend

Today, the Backend uses the repository Installation Id together with our App secret to request an ephemeral Access Token which it supplies to Restyler. This is great because Restyler doesn't care where it came from. All we have to do is look up the configured Access Token for the GitLab repository and supply it. Using long-lived tokens is inherently less secure, but because GitLab doesn't support anything else, we'd have no choice.

We'll need to have a known user with an access-token that we can find for a given repository. This basically means we can't support Organizations yet, since we're not maintaining organization memberships on our side -- we'll just naively match Owner names to `userGitLabUsername`s. Once we have the access/refresh tokens, we'll pass a refreshed access token to the CLI.

## 4- Restyler CLI

We need to generalize the API actions so we can inject a concrete representation for GitHub vs GitLab appropriately. The path to do this is relatively clear, but it will be high-effort.

We need to handle cloning. GitHub is great that you can clone with an access-token. If GitLab (et al) *don't* support this, we'll have to manage deploy keys... Gross.

**Comment by joneshf** [comment]
> if anyone is down to help, please reach out!

I'd love to have support for another service like GitLab! Let me know how I can help!

**Comment by pbrisbin** [comment]
> Let me know how I can help!

Awesome!

Generally speaking, engaging in this Issue is a great start. I'm looking for any of the following:

1. Someone to bounce ideas off of if/when I make progress in this direction
1. Someone with GitLab experience to answer questions when I'm not sure the best way forward with GitLab-specific behavior
1. Someone (if so inclined) to actually own the design and implementation of any `SVCS`\* abstractions in the code

I've done some local experimentation and feel good about (2) and (3) from the "design" above (and I already completed (1)), so if you wanted to get your hands dirty in actual code the place to investigate is (3).

This is actually not a bad way to help out since the `restyler` CLI is isolated and easily testable locally if you wanted to start experimenting with adding GitLab support there. If you're interested in that specifically, let me know and I can give more specific details and potential next steps.

Thanks!

\* *I've been trying to find a term for the abstraction over GitHub|GitLab|Bitbucket|etc. The only library I've found like this uses `vcs`, but that's not right: the VCS is git|svn|darcs|etc. At this point, I'm trying out `SVCS` for "Social Version Control System"... Let me know if you have any better ideas :)*

**Comment by pbrisbin** [comment]
I'm going to Close this Issue, unfortunately.

- Juggling the two APIs in Restyled will be a massive change
- Doing this via a user-specific OAuth token from login is a poor UX
- Cloning for GitLab will require managing SSH deploy keys
- GitHub continues to diverge from GitLab with Checks, Actions, Suggested Changes, etc -- leaning into those GitHub-specific features seems like more ROI than trying to support a unified, but simpler experience across GitHub/GitLab/Whatever

In general, GitHub's App functionality is just *really well done* and GitLab has nothing like it. So it's not a generalization problem to elegantly support both on a unified base, it's just (more than) twice the code to have the nice existing App-based path, *plus* something bespoke for however GitLab may work.

This all adds up to too much work to ever complete while this is still a free side-project. Maybe if we're making money some day, and GitLab support is a frequently-requested feature, we can pick this back up.

---

The offer of support for anyone who wants to own this initiative still stands though. If you're out there, let me know and I'll re-open and re-assign this Issue.
