### ISSUE TITLE
Force-push failed with "stale info"

### ISSUE THREAD

**Issue by pbrisbin** [restyled-io/restyled.io#79]
```
Switched to a new branch 'cp/tag-system-domains'
Switched to a new branch 'cp/tag-system-domains-restyled'
To https://github.com/frontrowed/megarepo.git
 ! [rejected]              cp/tag-system-domains-restyled -> cp/tag-system-domains-restyled (stale info)
error: failed to push some refs to 'https://...@github.com/frontrowed/megarepo.git'
We had trouble running a git command:
callProcess: git "push" "--force-with-lease" "origin" "cp/tag-system-domains-restyled" (exit 1): failed
```

Not sure what scenario leads to this.

**Comment by pbrisbin** [comment]
I think happened because the branch was deleted at _just about exactly_ the same time we tried to force-push-with-lease. So we just lost the race, wild.

**Comment by pbrisbin** [comment]
Close this as a failed race not worth trying to work around.

**Comment by badushaebrahim** [comment]
bro try pulling to the remote branch frist the  push remove stale brach error

**Comment by pbrisbin** [comment]
Thanks for the suggestion, see https://github.com/restyled-io/restyler/issues/88.

The key thing is that a Restyle is a full change onto the base. It's not designed (nor can it be) to be incremental on top of other Restylings. Therefore, two concurrent Restyles (which this error represents) cannot both be kept.

> I'm not sure what should happen here, it depends on what sort of ordering guarantees we we want to rely on...
>
> We could consider this a no-op: assuming a _later_ Restyler must've finished first, so our work can be safely discarded.
> 
> We could just `push --force`: assuming an _earlier_ Restyler must've finished first, so our work is more accurate and should overwrite.

What you're suggesting is functionally equivalent to the second approach. We don't know at that point if we're the later or earlier work. And pushing (or pull-pushing) will mess things up ~50% of the time.

We solved this by cancelling redundant builds. This is more efficient and avoids concurrent builds and so totally side-steps the issue. We can still lose races here or there, but it's (far) less frequent now, so we don't consider this an open Issue.
